FROM grafana/grafana:9.5.6-ubuntu 

LABEL maintainer "HaDN"
LABEL org.opencontainers.image.source=https://github.com/moophat/SVTECH_Projects_Container

USER root

RUN apt-get update -y && \
    apt-get -qq --no-install-recommends -y install nodejs npm && \
    apt-get autoclean

RUN npm install -g wizzy

RUN mkdir -p /opt/grafana-entities/dashboards \
 && mkdir -p /opt/grafana-entities/datasources \
 && mkdir /tmp/grafana-entities

COPY ./configs/plugins /var/lib/grafana/plugins
COPY ./configs/scripted_dashboards/service_detail_dashboard.js /usr/share/grafana/public/dashboards/service_detail_dashboard.js

COPY ./configs/grafana.ini /etc/grafana/grafana.ini
COPY ./configs/grafana-entities /tmp/grafana-entities

RUN cp -rf /tmp/grafana-entities/conf /opt/grafana-entities \
 && cp -rf /tmp/grafana-entities/dashboards /opt/grafana-entities \
 && rm -rf /tmp/grafana-entities

ENV MYSQL_HOST= \
    MYSQL_PORT=3306 \
    MYSQL_DB=grafana \
    MYSQL_USER=grafana \
    MYSQL_PASSWORD=juniper@123 \
    ADMIN_USER=thrukadmin \
    ADMIN_PASSWORD=thrukadmin \
    IMPORT_DEFAULT="false"

COPY ./run.sh /run.sh

ENTRYPOINT [ "/run.sh" ]
