version: '3.7'
services:
  grafana:
    image: hadnat/svtech_grafana:7.0.3
    container_name: svtech_grafana
    hostname: Grafana
    # volumes:

    environment:
      MYSQL_HOST: 10.98.0.132
      MYSQL_PORT: 3306
      MYSQL_DB: grafana
      MYSQL_USER: root
      MYSQL_PASSWORD: juniper@123
      ADMIN_USER: thrukadmin
      ADMIN_PASSWORD: thrukadmin
      IMPORT_DEFAULT: "true"
    restart: always
    ports:
      - 3000:3000
