version: '3.7'
services:

  httpd:
    image: hadnat/svtech_http_thruk:v1.0.0
    container_name: svtech_http_thruk

    environment:
      BACKEND_NAME: NMS
      BACKEND_ID: NMS
      BACKEND_TYPE: livestatus
      BACKEND_IP: 10.98.0.117
      BACKEND_PORT: 6558

    ports:
      - 80:80
