{
 "title": "Device Dashboard Overview",
 "tags": [ "Host_info" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "SHOW datasources;" },
   {
    "name": "device_type",
    "label": "Device Type",
    "query": "SELECT hosts.vars.device_type FROM $datasource;"
   },
   {
    "name": "hostname",
    "label": "Device name",
    "query": "SELECT hosts.display_name FROM $datasource WHERE vars.device_type = $device_type;"
   },
   {
    "name": "address",
    "label": "IP address",
    "query": "SELECT hosts.address FROM $datasource WHERE display_name = $hostname AND vars.device_type = $device_type;"
   },
   {
    "name": "interface",
    "label": "Interface-check",
    "query": "SELECT services.display_name FROM $datasource WHERE display_name ~ IfCheck AND host_name ~ $hostname;"
   },
   {
    "name": "FPC",
    "label": "FPC",
    "query": "SELECT services.display_name FROM $datasource WHERE host_name ~ $hostname AND display_name ~ FPC;"
   },
   { "name": "grafana_ds", "query": "icinga2-report-datasource" }
  ]
 },
 "panels": [
  {
   "title": "$hostname Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "hostname",
   "collapsed": true,
   "panels": [
    {
     "title": "STATUS",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "hostalive",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "pl" }
       ]
      }
     ]
    },
    {
     "title": "Ping4",
     "type": "graph",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 1 },
     "yaxes": [
      { "format": "s", "label": "RTA" }
     ],
     "targets": [
      {
       "alias": "RTA",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "ping4",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SELECT mean(\"value\") FROM \"ping4\" WHERE (\"metric\" = 'pl' AND \"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "rta" }
       ],
       "timeField": "@timestamp"
      },
      {
       "alias": "PL",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "ping4",
       "query": "SELECT mean(\"value\") FROM \"ping4\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'pl') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "pl" }
       ]
      }
     ]
    },
    {
     "title": "CPU LOAD",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_service",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "service" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "snmp",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'CPU RE0' AND \"service\" = 'Juniper CPU ACX') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^CPU.*.RE.*/" },
        { "condition": "AND", "key": "metric", "operator": "!~", "value": "/^CPU.*.RE\\d_mem\\d.*/" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "MEMORY",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_service",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "service" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "snmp",
       "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /Juniper Memory~/ AND \"metric\" = 'MEM_RE0') AND $timeFilter GROUP BY time($__interval) fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^MEM.*.RE.*/" },
        { "condition": "AND", "key": "metric", "operator": "!~", "value": "/^MEM.*.RE\\d_mem\\d.*/" }
       ],
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "TEMPERATURE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "$tag_service",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "service" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "snmp",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=~", "value": "/TEMP.*.RE.*|Temp_Chassis/" },
        { "condition": "AND", "key": "metric", "operator": "!~", "value": "/^TEMP.*.RE\\d_mem\\d.*/" }
       ],
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "CPU LOAD FPC",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "CPU Load $tag_service",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "service" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "snmp",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'CPU RE0' AND \"service\" = 'Juniper CPU ACX') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "CPU_FPC" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "MEM LOAD FPC",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "MEM Load $tag_service",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "service" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "snmp",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SELECT last(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'MEM_FPC') AND $timeFilter GROUP BY time($__interval), \"service\" fill(previous)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "MEM_FPC" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "TEMPERATURE FPC",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "Temperature $tag_service",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "service" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "snmp",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "SELECT mean(\"value\") FROM \"snmp\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'CPU RE0' AND \"service\" = 'Juniper CPU ACX') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "TEMP_FPC" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Bandwith Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bandwidth Total Physical Interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$hostname-total-InBit",
       "groupBy": [
        { "params": [ "2m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Interface-check-command",
       "query": "SELECT SUM(mean) FROM (SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" = '$hostname' AND \"service\" !~ /.*ae.*/ AND \"metric\" = 'in_bits') AND $timeFilter GROUP BY time(2m), service) GROUP BY time(2m);\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
        { "condition": "AND", "key": "service", "operator": "!=", "value": "ae" }
       ]
      },
      {
       "alias": "$hostname-total-OutBit",
       "groupBy": [
        { "params": [ "2m" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "Interface-check-command",
       "query": "SELECT SUM(mean) FROM (SELECT mean(\"value\") FROM \"Interface-check-command\" WHERE (\"hostname\" = '$hostname' AND \"service\" !~ /.*ae.*/ AND \"metric\" = 'out_bits') AND $timeFilter GROUP BY time(2m), service) GROUP BY time(2m);\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
        { "condition": "AND", "key": "service", "operator": "!=", "value": "ae" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "interface",
   "collapsed": true,
   "panels": [
    {
     "title": "$interface Infomation",
     "type": "table",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "segments": [
        "SELECT",
        "plugin_output",
        "FROM",
        "LiveStatus",
        "WHERE",
        "host_name",
        "=",
        "$hostname",
        "AND",
        "display_name",
        "=",
        "IfCheck-[[interface]]",
        "*",
        "*",
        "*"
       ],
       "target": "services",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$hostname-$interface-InBit",
       "measurement": "Interface-check-command",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[interface]]$/" }
       ]
      },
      {
       "alias": "$hostname-$interface-OutBit",
       "measurement": "Interface-check-command",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^IfCheck-[[interface]]$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}