FROM python:3.6.11-slim-buster
LABEL maintainer "HaDN"
LABEL org.opencontainers.image.source=https://github.com/moophat/SVTECH_Projects_Container
USER root

RUN apt-get -y update && \
    apt-get -qq --no-install-recommends install vim && \
    apt-get autoclean

COPY ./requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt --no-cache-dir

RUN mkdir -p /etc/rundeck \
             /var/lib/rundeck/jsnapy \
             /etc/jsnapy \
             /opt/SVTECH-Junos-Automation/addition_toolkit/rundeck_options_API \
             /opt/SVTECH-Junos-Automation/module_utils

COPY ./rundeck_options_API/ /opt/SVTECH-Junos-Automation/addition_toolkit/rundeck_options_API
COPY ./module_utils/ /opt/SVTECH-Junos-Automation/module_utils

EXPOSE 1111

WORKDIR /opt/SVTECH-Junos-Automation/addition_toolkit/rundeck_options_API
ENTRYPOINT [ "python", "rundeck_options_API.py" ]