apiVersion: v2
annotations:
  category: Frontend
name: rundeck
description: SVTECH Rundeck
engine: gotpl

dependencies:
  - name: common
    repository: file://../common
    tags:
      - bitnami-common
    version: 1.x.x

version: 1.0.0
appVersion: "v1.1.0"
