global:
  sharedVolume:
    enabled: false

timezone: Asia/Ho_Chi_Minh

init:
  image:
    registry: docker.io
    repository: busybox
    tag: "1.33"
    pullPolicy: IfNotPresent

image:
  repository: svtechnmaa/svtech_icinga2
  tag: "latest"
  pullPolicy: IfNotPresent
  # debug: true

clusterDomain: cluster.local
commonAnnotations: {}
commonLabels: {}

## architecture: standalone or distribute.
## - standalone: just master
## - distribute: distributed monitoring with master-satellite cluster
architecture: distribute


### Master
master:
  replicaCount: 3

  updateStrategy: RollingUpdate
  podManagementPolicy: OrderedReady
  podAffinityPreset: ""
  podAntiAffinityPreset: soft

  nodeAffinityPreset:
    ## Node affinity type
    ## Allowed values: soft, hard
    type: ""
    ## Node label key to match
    ## E.g.
    ## key: "kubernetes.io/e2e-az-name"
    ##
    key: ""
    ## Node label values to match
    ## E.g.
    ## values:
    ##   - e2e-az1
    ##   - e2e-az2
    ##
    values: []

  ## Affinity for pod assignment
  ## Note: podAffinityPreset, podAntiAffinityPreset, and  nodeAffinityPreset will be ignored when it's set
  ##
  affinity: {}

  ## Node labels for pod assignment
  nodeSelector: {}

  ## Tolerations for pod assignment
  tolerations: []

  ## Extra volumes to add to the deployment
  extraVolumes: []

  ## Extra volume mounts to add to the container
  extraVolumeMounts: []

  securityContext:
    enabled: false
    fsGroup: 0
    runAsUser: 0

  resources:
    limits: {}
    #   cpu: 100m
    #   memory: 128Mi
    requests: {}
    #   cpu: 100m
    #   memory: 128Mi


  livenessProbe:
    enabled: false
    initialDelaySeconds: 180
    periodSeconds: 45
    timeoutSeconds: 30
    successThreshold: 1
    failureThreshold: 6
  readinessProbe:
    enabled: false
    initialDelaySeconds: 60
    periodSeconds: 45
    timeoutSeconds: 30
    successThreshold: 1
    failureThreshold: 6

  ## Custom Liveness probe
  customLivenessProbe: {}

  ## Custom Readiness probe
  customReadinessProbe: {}

  ## Container ports
  containerPorts:
    icinga2Api: 5665
    livestatus: 6558

  # persistence:
  #   enabled: true
  #   # # mountPath on Container
  #   # mountPath: /etc/icinga2

  #   # hostPath: mount path on Host
  #   hostPath: /opt/k8s_configurations/icinga2

  influxdb_connection:
    enable: false
    # influxdb_host: "influxdb"
    influxdb_port: 8086
    influxdb_database: influxdb_nms
    influxdb_user: juniper
    influxdb_password: juniper@123

  ido_connection:
    enable: false
    # ido_host: "mariadb"
    ido_port: 3306
    ido_user: icinga
    ido_password: icinga
    ido_database: icinga
    ido_catagories: '["DbCatConfig", "DbCatState", "DbCatAcknowledgement", "DbCatComment", "DbCatDowntime", "DbCatEventHandler", "DbCatFlapping", "DbCatNotification", "DbCatProgramStatus", "DbCatRetention", "DbCatStateHistory"]'
    ido_cleanup_statehistory: 90d
    ido_cleanup_notificaion: 90d
    ido_cleanup_servicecheck: 7d

  notifications:
    enable: false
    # mailhub_host: "postfix"
    mailhub_port: 25
    relay_email: "ha.do@svtech.com.vn"

  service:
    ## Service type
    ##
    type: ClusterIP

    port:
      icinga2Api: 5665
      livestatus: 6558

    nodePorts:
      icinga2Api: ""
      livestatus: ""

    # loadBalancerIP:
    # loadBalancerSourceRanges:
    # - 10.10.10.0/24

    ## Set the Cluster IP to use
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#choosing-your-own-ip-address
    ##
    # clusterIP: None
    ## Provide any additional annotations which may be required
    ##
    annotations: {}
    ## Set the service SessionAffinity for session stickiness
    ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#proxy-mode-userspace
    # sessionAffinity: ClientIP

    ## Customize the SessionAffinity configuration. The default value for sessionAffinityConfig.clientIP.timeoutSeconds is 10800 (3 hours)
    # sessionAffinityConfig:
    #   clientIP:
    #     timeoutSeconds: 300

# ### Satellite
# satellite:
#   replicaCount: 0

#   updateStrategy: RollingUpdate
#   podManagementPolicy: OrderedReady
#   podAffinityPreset: ""
#   podAntiAffinityPreset: soft

#   ## Node affinity preset
#   nodeAffinityPreset:
#     ## Node affinity type
#     ## Allowed values: soft, hard
#     type: ""
#     ## Node label key to match
#     ## E.g.
#     ## key: "kubernetes.io/e2e-az-name"
#     ##
#     key: ""
#     ## Node label values to match
#     ## E.g.
#     ## values:
#     ##   - e2e-az1
#     ##   - e2e-az2
#     ##
#     values: []

#   ## Affinity for pod assignment
#   ## Note: podAffinityPreset, podAntiAffinityPreset, and  nodeAffinityPreset will be ignored when it's set
#   affinity: {}

#   ## Node labels for pod assignment
#   nodeSelector: {}

#   ## Tolerations for pod assignment
#   tolerations: []

#   ## Extra volumes to add to the deployment
#   extraVolumes: []

#   ## Extra volume mounts to add to the container
#   extraVolumeMounts: []

#   securityContext:
#     enabled: false
#     fsGroup: 0
#     runAsUser: 0

#   resources:
#     limits: {}
#     #   cpu: 100m
#     #   memory: 128Mi
#     requests: {}
#     #   cpu: 100m
#     #   memory: 128Mi


#   livenessProbe:
#     enabled: true
#     initialDelaySeconds: 180
#     periodSeconds: 45
#     timeoutSeconds: 30
#     successThreshold: 1
#     failureThreshold: 6
#   readinessProbe:
#     enabled: true
#     initialDelaySeconds: 60
#     periodSeconds: 45
#     timeoutSeconds: 30
#     successThreshold: 1
#     failureThreshold: 6

#   ## Custom Liveness probe
#   ##
#   customLivenessProbe: {}

#   ## Custom Readiness probe
#   ##
#   customReadinessProbe: {}
