apiVersion: v2
annotations:
  category: icingaweb
name: icingaweb
engine: gotpl

dependencies:
  - name: common
    repository: file://../common
    tags:
      - bitnami-common
    version: 1.x.x
  - name: icinga2
    repository: file://../icinga2
    version: 1.0.0

version: 1.0.0
appVersion: "v1.0.0"
