FROM php:8.1-apache

LABEL org.opencontainers.image.source=https://github.com/moophat/SVTECH_Projects_Container

RUN a2enmod headers \
&& a2enmod rewrite

RUN apt-get update && \
    apt-get install -y -qq --no-install-recommends wget expect sqlite3 rsync graphviz && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

COPY ./scripts/install_nagvis.sh /var/tmp/

# Dowload and Install nagvis
RUN cd /var/tmp && \
    wget https://www.nagvis.org/share/nagvis-1.9.34.tar.gz && \
    tar -xvf nagvis-1.9.34.tar.gz && \
    chmod -R 775 nagvis-1.9.34 && \
    cp -rf /var/tmp/install_nagvis.sh nagvis-1.9.34 && \
    rm -rf /var/tmp/nagvis-1.9.34.tar.gz &&\
    chmod +x install_nagvis.sh && \
    mkdir -p /etc/icinga2 /usr/share/nagvis && \
    cd /var/tmp/nagvis-1.9.34 && \
    ./install_nagvis.sh
    
# Config nagvis.ini.php file and add auth.db file to nagvis
COPY ./nagvis /var/tmp/nagvis

# Define ENV for backend
ENV BACKEND_NAME=NMS \
    BACKEND_ID=NMS \
    BACKEND_TYPE=mklivestatus \
    BACKEND_IP= \
    BACKEND_PORT=6558 \
    PHP_MEMORY_LIMIT_M=1024

# Add nagvis-make-admin file
RUN cp /var/tmp/nagvis-1.9.34/nagvis-make-admin /usr/share/nagvis/etc && \
    # Config nagvis.ini.php file and add auth.db file to nagvis
    cp -rf /var/tmp/nagvis/nagvis.ini.php /usr/share/nagvis/etc/nagvis.ini.php && \
    cp -rf /var/tmp/nagvis/auth.db /usr/share/nagvis/etc/auth.db && \
    # Add nagvis.conf to apache2/conf-enabled/
    cp -rf /var/tmp/nagvis/nagvis.conf /etc/apache2/conf-available/nagvis.conf && \
    ln -s /etc/apache2/conf-available/nagvis.conf /etc/apache2/conf-enabled/nagvis.conf &&\
    # Add default images file to nagvis 
    cp -rf /var/tmp/nagvis/images/iconsets /usr/share/nagvis/share/userfiles/images/ && \
    cp -rf /var/tmp/nagvis/images/shapes /usr/share/nagvis/share/userfiles/images/ && \
    # Replace some js files to nagvis
    cp -rf /var/tmp/nagvis/nagvis-js/* /usr/share/nagvis/share/frontend/nagvis-js/js/ && \
    cp -rf /var/tmp/nagvis/maps/* /usr/share/nagvis/etc/maps/ && \
    rm -rf /var/tmp/nagvis-1.9.34 && \
    # Grant admin's privileges to thrukadmin
    cd /usr/share/nagvis/etc && \
    ./nagvis-make-admin thrukadmin && \
    # Config php.ini 
    cp -rf /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini && \
    sed -i "s/memory_limit =.*/memory_limit = ${PHP_MEMORY_LIMIT_M}M/g" /usr/local/etc/php/php.ini

EXPOSE 80

COPY ./apache/apache2.conf /etc/apache2/apache2.conf

COPY ./scripts/entrypoint.sh /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
