FROM syncthing/syncthing:latest

LABEL org.opencontainers.image.source=https://github.com/moophat/SVTECH_Projects_Container

EXPOSE 8384 22000/tcp 22000/udp 21027/udp

VOLUME ["/var/syncthing"]

RUN apk add --no-cache ca-certificates curl libcap su-exec tzdata bind-tools

COPY ./scripts/docker-entrypoint.sh /bin/entrypoint.sh
COPY ./scripts/default-attributes.sh /bin/default-attributes.sh
COPY ./scripts/auto_discovery_node.sh /bin/auto_discovery_node.sh
COPY ./scripts/auto_share_folder.sh /bin/auto_share_folder.sh

ENV PUID=1000 PGID=1000 HOME=/var/syncthing

HEALTHCHECK --interval=1m --timeout=10s \
  CMD curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1

ENV STGUIADDRESS=0.0.0.0:8384
RUN chmod 755 /bin/entrypoint.sh /bin/default-attributes.sh /bin/auto_discovery_node.sh /bin/auto_share_folder.sh
ENTRYPOINT ["/bin/entrypoint.sh", "/bin/syncthing", "-home", "/var/syncthing/config"]
