apiVersion: v2
annotations:
  category: API
name: rundeck-option-provider
description: SVTECH Rundeck Option Provider
engine: gotpl

dependencies:
  - name: common
    repository: file://../common
    tags:
      - bitnami-common
    version: 1.x.x

version: 1.0.0
appVersion: "v1.0.0"
