global:
  sharedVolume:
    enabled: false

timezone: Asia/Ho_Chi_Minh

image:
  repository: svtechnmaa/svtech_http_thruk
  tag: "latest"

  pullPolicy: IfNotPresent
  # debug: true

clusterDomain: cluster.local
commonAnnotations: {}
commonLabels: {}

replicaCount: 3

updateStrategy: RollingUpdate
podManagementPolicy: OrderedReady
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  ## Node affinity type
  ## Allowed values: soft, hard
  type: ""
  ## Node label key to match
  ## E.g.
  ## key: "kubernetes.io/e2e-az-name"
  ##
  key: ""
  ## Node label values to match
  ## E.g.
  ## values:
  ##   - e2e-az1
  ##   - e2e-az2
  ##
  values: []


## Affinity for pod assignment
## Note: podAffinityPreset, podAntiAffinityPreset, and  nodeAffinityPreset will be ignored when it's set
##
affinity: {}

## Node labels for pod assignment
nodeSelector: {}

## Tolerations for pod assignment
tolerations: []

## Extra volumes to add to the deployment
extraVolumes: []

## Extra volume mounts to add to the container
extraVolumeMounts: []

securityContext:
  enabled: false
  fsGroup: 0
  runAsUser: 0

resources:
  limits: {}
  #   cpu: 100m
  #   memory: 128Mi
  requests: {}
  #   cpu: 100m
  #   memory: 128Mi


livenessProbe:
  enabled: false
  initialDelaySeconds: 180
  periodSeconds: 45
  timeoutSeconds: 30
  successThreshold: 1
  failureThreshold: 6
readinessProbe:
  enabled: false
  initialDelaySeconds: 60
  periodSeconds: 45
  timeoutSeconds: 30
  successThreshold: 1
  failureThreshold: 6

## Custom Liveness probe
customLivenessProbe: {}

## Custom Readiness probe
customReadinessProbe: {}

## Container ports
containerPorts:
  # icinga2Api: 5665
  # livestatus: 6558


service:
  ## Service type
  ##
  type: ClusterIP
  port: 80

  # loadBalancerIP:
  # loadBalancerSourceRanges:
  # - 10.10.10.0/24

  # externalIPs: ["10.98.0.143"]

  ## Set the Cluster IP to use
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#choosing-your-own-ip-address
  ##
  # clusterIP: None
  ## Provide any additional annotations which may be required
  ##
  annotations: {}
  ## Set the service SessionAffinity for session stickiness
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#proxy-mode-userspace
  sessionAffinity: ClientIP

  # ## Customize the SessionAffinity configuration. The default value for sessionAffinityConfig.clientIP.timeoutSeconds is 10800 (3 hours)
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 7200

thrukConfig:
  backendName: NMS
  backendId: NMS
  backendType: livestatus
  # backendIp: 10.98.0.117  # default is icinga2 cluster name
  backendPort: 6558

# [Optional] Alternative for thrukConfig above
thruk_backend_config:
  enable: false
  configuration: |-
    <Component Thruk::Backend>
        <peer>
          name      = NMS
          id        = NMS
          type      = livestatus
          <options>
            peer   = 10.98.0.117:6558
          </options>
        </peer>
    </Component>

    <Component Thruk::Backend>
        <peer>
          name      = NMS-116
          id        = NMS-116
          type      = livestatus
          <options>
            peer   = 10.98.0.116:6558
          </options>
        </peer>
    </Component>

    <configtool>
      core_type     = icinga2
      core_conf     = /etc/icinga2/icinga2.conf
      obj_check_cmd = /run/icinga2/cmd/icinga2.cmd -v /run/icinga2/cmd/icinga2.cmd
    </configtool>

# ## Proxy config
# proxy:
#   enable: true
#   configuration: |-
#     {{- $releaseName := .Release.Name }}
#     <Location "/report">
#             RequestHeader set Host "http://{{ $releaseName }}-icinga2-report/report"
#             ProxyPass "http://{{ $releaseName }}-icinga2-report:8888" connectiontimeout=600 timeout=600 Keepalive=On
#     </Location>

#     <Location "/grafana">
#             RewriteEngine On
#             RewriteRule .* - [E=PROXY_USER:%{LA-U:REMOTE_USER},NS]
#             RequestHeader set X-WEBAUTH-USER "%{PROXY_USER}e"

#             RequestHeader unset Authorization

#             ProxyPass "http://{{ $releaseName }}-grafana:3000"
#             ProxyPassReverse "http://{{ $releaseName }}-grafana:3000"
#     </Location>

#     <Location "/grafana/send_request">
#             ProxyPass "http://{{ $releaseName }}-icinga2-report:8888"
#             ProxyPassReverse "http://{{ $releaseName }}-icinga2-report:8888"
#     </Location>

#     <Location "/rundeck">
#             ProxyPass http://{{ $releaseName }}-rundeck:4440/rundeck
#             ProxyPassReverse http://{{ $releaseName }}-rundeck:4440/rundeck
#     </Location>

#     <Location "/csv">
#             ProxyPass "http://{{ $releaseName }}-csv-view:8000"
#             ProxyPassReverse "http://{{ $releaseName }}-csv-view:8000"
#     </Location>

#     <Location "/nagvis">
#             ProxyPass http://{{ $releaseName }}-nagvis/nagvis
#             ProxyPassReverse http://{{ $releaseName }}-nagvis/nagvis
#     </Location>

#     <Location "/gitlist">
#             ProxyPass http://{{ $releaseName }}-gitlist/gitlist
#             ProxyPassReverse http://{{ $releaseName }}-gitlist/gitlist
#     </Location>
