version: '3'

networks:
  default:
    name: snmp-manager

services:
  snmp-manager:
    image: ${repository}:${tag}
    environment:
      ICINGA_HOST: ${ICINGA_HOST:-localhost}
      ICINGA_PORT: ${ICINGA_PORT:-5665}
      ICINGA_USER: ${ICINGA_USER:-icingaweb}
      ICINGA_PASSWORD: ${ICINGA_PASSWORD:-icingaweb}
      MYSQL_DBI_ENABLE: ${MYSQL_DBI_ENABLE:-0}
      MYSQL_DBI_HOST: ${MYSQL_DBI_HOST:-localhost}
      MYSQL_DBI_PORT: ${MYSQL_DBI_PORT:-3306}
      MYSQL_DBI_DATABASE: ${MYSQL_DBI_DATABASE:-snmptt}
      MYSQL_DBI_TABLE: ${MYSQL_DBI_TABLE:-snmptt}
      MYSQL_DBI_TABLE_UNKNOWN: ${MYSQL_DBI_TABLE_UNKNOWN:-snmptt_unknown}
      MYSQL_DBI_USERNAME: ${MYSQL_DBI_USERNAME:-snmptt}
      MYSQL_DBI_PASSWORD: ${MYSQL_DBI_PASSWORD:-snmptt}
    ports:
      - "162:162/udp"
    entrypoint: sh -c /data/scripts/entrypoint.sh
    volumes:
      - snmp-manager-config:/etc/snmptt

volumes:
  snmp-manager-config:
