
apiVersion: v1
kind: Secret
metadata:
  name: es-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: '{{ .Values.global.elasticsearch.adminUser.name }}'    # required field for kubernetes.io/basic-auth
  password: '{{ .Values.global.elasticsearch.adminUser.pass }}' # required field for kubernetes.io/basic-auth
  roles: {{ .Values.global.elasticsearch.adminUser.role }}  # optional, not part of kubernetes.io/basic-auth