FROM alpine:3.13

LABEL org.opencontainers.image.source=https://github.com/moophat/SVTECH_Projects_Container

RUN apk add --no-cache postfix supervisor tzdata \
 && rm -rf /var/cache/apk/*

COPY ./scripts/entrypoint.sh /entrypoint.sh

COPY ./supervisord.conf /etc/supervisord.conf

ENV MTP_RELAY=smtp-relay.gmail.com \
    MTP_PORT=25 \
    MTP_USER= \
    MTP_PASS= \
    MTP_MESSAGE_SIZE_LIMIT=102400000 \
    MTP_MAILBOX_SIZE_LIMIT=51200000000 \
    MAIL_LOG_FILE=/var/log/maillog \
    # Optional
    MTP_BANNER= \
    MTP_INTERFACES= \
    MTP_DESTINATION= \
    MTP_RELAY_DOMAINS=

USER root
EXPOSE 25

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
