#!/bin/env sh
###-INIT-FOLDER-###
export LIST_FOLDER=${LIST_FOLDER:="SVTECH"}

###-HEADLESS-SERVICE-###
export HEADLESS_SERVICE_NAME=${HEADLESS_SERVICE_NAME:="syncthing-headless.default.svc.cluster.local"}

###-AUTO-DISCOVERY-###
export AUTO_DISCOVERY_NODE_INTERVAL=${AUTO_DISCOVERY_NODE_INTERVAL:="60"}
export AUTO_SHARE_FOLDER_INTERVAL=${AUTO_SHARE_FOLDER_INTERVA:="60"}

###-PROCESS-ATTRIBUTES-###
export STGUIAPIKEY=${STGUIAPIKEY:="juniper@123"}
export STGUIUSER=${STGUIUSER:="juniper"}
export STGUIPASSWORD=${STGUIPASSWORD:="juniper@123"}
export RESPONSE_CODE=${RESPONSE_CODE:="0"}
export INTERVAL_HEALTHCHECK=${INTERVAL_HEALTHCHECK:="5"}
export TIMEOUT=${TIMEOUT:="30"}

###-DEFAULT-FOLDERS-ATTRIBUTES-###
export FOLDERS_RESCANINTERVALS=${FOLDERS_RESCANINTERVALS:="3600"}
export FOLDERS_FSWATCHERENABLED=${FOLDERS_FSWATCHERENABLED:="true"}
export FOLDERS_FSWATCHERDELAYS=${FOLDERS_FSWATCHERDELAYS:="2"}
export FOLDERS_VERSIONING_TYPE=${FOLDERS_VERSIONING_TYPE:="trashcan"}
export FOLDERS_VERSIONING_PARAMS_CLEANOUTDAYS=${FOLDERS_VERSIONING_PARAMS_CLEANOUTDAYS:="0"}
export FOLDERS_VERSIONING_CLEANUPINTERVALS=${FOLDERS_VERSIONING_CLEANUPINTERVALS:="3600"}
export FOLDERS_VERSIONING_FSPATH=${FOLDERS_VERSIONING_FSPATH:=""}
export FOLDERS_VERSIONING_FSTYPE=${FOLDERS_VERSIONING_FSTYPE:="basic"}
export FOLDERS_MAXCONFLICTS=${FOLDERS_MAXCONFLICTS:="10"}
export FOLDERS_COPYOWNERSHIPFROMPARENT=${FOLDERS_COPYOWNERSHIPFROMPARENT:="true"}
export FOLDERS_MAXCONCURRENTWRITES=${FOLDERS_MAXCONCURRENTWRITES:="30"}
export FOLDERS_CASESENSITIVEFS=${FOLDERS_CASESENSITIVEFS:="false"}
export FOLDERS_JUNCTIONSASDIRS=${FOLDERS_JUNCTIONSASDIRS:="false"}
export FOLDERS_SYNCOWNERSHIP=${FOLDERS_SYNCOWNERSHIP:="true"}
export FOLDERS_SENDOWNERSHIP=${FOLDERS_SENDOWNERSHIP:="true"}
export FOLDERS_SYNCXATTRS=${FOLDERS_SYNCXATTRS:="true"}
export FOLDERS_SENDXATTRS=${FOLDERS_SENDXATTRS:="true"}
export FOLDERS_XATTRFILTER_ENTRIES=${FOLDERS_XATTRFILTER_ENTRIES:="[ { \"match\": \"security.*\", \"permit\": false }, { \"match\": \"*\", \"permit\": true } ]"}
export FOLDERS_XATTRFILTER_MAXSINGLEENTRYSIZE=${FOLDERS_XATTRFILTER_MAXSINGLEENTRYSIZE:="1024"}
export FOLDERS_XATTRFILTER_MAXTOTALSIZE=${FOLDERS_XATTRFILTER_MAXTOTALSIZE:="4096"}

###-DEFAULT-DEVICES-ATTRIBUTES-###
export DEVICE_DEVICEID=${DEVICE_DEVICEID:=""}
export DEVICE_NAME=${DEVICE_NAME:=""}
export DEVICE_ADDRESSES=${DEVICE_ADDRESSES:="dynamic"}
export DEVICE_COMPRESSION=${DEVICE_COMPRESSION:="metadata"}
export DEVICE_CERTNAME=${DEVICE_CERTNAME:=""}
export DEVICE_INTRODUCER=${DEVICE_INTRODUCER:="false"}
export DEVICE_SKIPINTRODUCTIONREMOVALS=${DEVICE_SKIPINTRODUCTIONREMOVALS:="true"}
export DEVICE_INTRODUCEDBY=${DEVICE_INTRODUCEDBY:=""}
export DEVICE_PAUSED=${DEVICE_PAUSED:="false"}
export DEVICE_ALLOWEDNETWORKS=${DEVICE_ALLOWEDNETWORKS:="0.0.0.0/0"}
export DEVICE_AUTOACCEPTFOLDERS=${DEVICE_AUTOACCEPTFOLDERS:="true"}
export DEVICE_MAXSENDKBPS=${DEVICE_MAXSENDKBPS:="0"}
export DEVICE_MAXRECVKBPS=${DEVICE_MAXRECVKBPS:="0"}
export DEVICE_IGNOREDFOLDERS=${DEVICE_IGNOREDFOLDERS:="[]"}
export DEVICE_MAXREQUESTKIB=${DEVICE_MAXREQUESTKIB:="0"}
export DEVICE_UNTRUSTED=${DEVICE_UNTRUSTED:="false"}
export DEVICE_REMOTEGUIPORT=${DEVICE_REMOTEGUIPORT:="0"}

###-OPTIONS-ATTRIBUTES-###
export OPTION_LISTENPORT=${OPTION_LISTENPORT:="22000"}
export OPTION_LISTENADDRESSES=${OPTION_LISTENADDRESSES:="[ \"tcp://0.0.0.0:${OPTION_LISTENPORT}\", \"quic://0.0.0.0:${OPTION_LISTENPORT}\" ]"}
export OPTION_GLOBALANNOUNCESERVERS=${OPTION_GLOBALANNOUNCESERVERS:=""}
export OPTION_GLOBALANNOUNCEENABLED=${OPTION_GLOBALANNOUNCEENABLED:="false"}
export OPTION_LOCALANNOUNCEENABLED=${OPTION_LOCALANNOUNCEENABLED:="true"}
export OPTION_LOCALANNOUNCEMCADDR=${OPTION_LOCALANNOUNCEMCADDR:="[ff12::8384]:${OPTION_LOCALANNOUNCEPORT}"}
export OPTION_RECONNECTIONINTERVALS=${OPTION_RECONNECTIONINTERVALS:="60"}
export OPTION_RELAYSENABLED=${OPTION_RELAYSENABLED:="false"}
export OPTION_RELAYRECONNECTINTERVALM=${OPTION_RELAYRECONNECTINTERVALM:="10"}
export OPTION_STARTBROWSER=${OPTION_STARTBROWSER:="true"}
export OPTION_NATENABLED=${OPTION_NATENABLED:="true"}
export OPTION_NATLEASEMINUTES=${OPTION_NATLEASEMINUTES:="60"}
export OPTION_NATRENEWALMINUTES=${OPTION_NATRENEWALMINUTES:="30"}
export OPTION_NATTIMEOUTSECONDS=${OPTION_NATTIMEOUTSECONDS:="10"}
export OPTION_URACCEPTED=${OPTION_URACCEPTED:="-1"}
export OPTION_AUTOUPGRADEINTERVALH=${OPTION_AUTOUPGRADEINTERVALH:="0"}
export OPTION_PROGRESSUPDATEINTERVALS=${OPTION_PROGRESSUPDATEINTERVALS:="24"}
export OPTION_ALWAYSLOCALNETS=${OPTION_ALWAYSLOCALNETS:=""}
export OPTION_OVERWRITEREMOTEDEVICENAMESONCONNECT=${OPTION_OVERWRITEREMOTEDEVICENAMESONCONNECT:="true"}
export OPTION_CRASHREPORTINGENABLED=${OPTION_CRASHREPORTINGENABLED:="false"}
export OPTION_DATABASETUNING=${OPTION_DATABASETUNING:="auto"}
export OPTION_ANNOUNCELANADDRESSES=${OPTION_ANNOUNCELANADDRESSES:="true"}
export OPTION_CONNECTIONLIMITENOUGH=${OPTION_CONNECTIONLIMITENOUGH:="0"}
export OPTION_CONNECTIONLIMITMAX=${OPTION_CONNECTIONLIMITMAX:="0"}
