{{- if and .Values.persistence.enabled ( eq .Values.persistence.storageClass "mariadb" ) }}
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: mariadb
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# allowVolumeExpansion: true

{{- $namespace := .Release.Namespace }}

{{- range $index, $topping := until (int .Values.replicaCount) }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ $namespace }}-data-mariadb-{{ $index }}"
  labels:
    app.kubernetes.io/name: mariadb-galera
    statefulset.kubernetes.io/pod-name: "{{ $.Release.Name }}-mariadb-galera-{{ $index }}"
spec:
  # storageClassName: {{ $namespace }}-mariadb
  storageClassName: mariadb
  capacity:
    storage: {{ $.Values.persistence.size | quote }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    # path: {{ $.Values.persistence.hostPath | quote }}
    path: {{ $.Values.persistence.hostPath }}/{{ $namespace }}/

  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: node_id
  #         operator: In
  #         values:
  #         - "{{ $index }}"

{{- end }}
{{- end }}
