version: '3.7'
services:

  httpd:
    image: ${REGISTRY}/svtechnmaa/svtech_http_thruk:latest
    container_name: svtech_http_thruk
    # volumes:
    #   - "./config/etc/httpd/conf.d/proxy.conf:/etc/apache2/sites-enabled/proxy.conf"
    #   - "./config/etc/httpd/conf.d/flask_static.conf:/etc/apache2/sites-enabled/flask_static.conf"
    #   - "./config/etc/php.ini:/usr/local/etc/php/php.ini"
    #   - "./config/var/www/html:/var/www/html"
    #   - "./config/etc/thruk/thruk_local.conf:/etc/thruk/thruk_local.conf"
    #   - "./config/etc/thruk/cgi.cfg:/etc/thruk/cgi.cfg"
    #   - "./config/etc/thruk/htpasswd:/etc/thruk/htpasswd"
    #   - "./config/usr/share/thruk/menu.conf:/usr/share/thruk/menu.conf"
    #   - "/opt/SVTECH-Junos-Automation:/opt/SVTECH-Junos-Automation"
    ports:
      - 80:80
    # env_file:
    #   - ./.env
    restart: always

  rundeck:
    image: rundeck/rundeck:4.1.0
    container_name: svtech_rundeck
    environment:
      # RUNDECK_SERVER_CONTEXT_PATH: /rundeck
      RUNDECK_GRAILS_URL: http://10.98.0.140:4440/rundeck
      # RUNDECK_SERVER_UUID: 00000000-000000000-0000-000000000001
      RUNDECK_SERVER_ADDRESS: "0.0.0.0"

    # entrypoint:
    #   - /bin/bash
    #   - -c
    #   - "sleep 100000"
    ports:
      - 4440:4440
