apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: icinga2-report
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.updateStrategy }}
    {{- if (eq "Recreate" .Values.updateStrategy) }}
    rollingUpdate: null
    {{- end }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: icinga2-report
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: icinga2-report
    spec:
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- end }}

      containers:
        - name: icinga2-report
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.image ) }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
          {{- end }}

          ports:
            - name: icinga2-report
              containerPort: 8888
          env:
            - name: TZ
              value: {{ include "common.timezone" ( dict "timezone" .Values.timezone "global" .Values.global) }}

          volumeMounts:
            {{- if .Values.datasources }}
            - name: datasources
              mountPath: /etc/icinga2-report/datasources.yml
              subPath: datasources.yml
            {{- end }}

            {{- if .Files.Glob "files/auth" }}
            - name: auth
              mountPath: /etc/icinga2-report/auth
              subPath: auth
            {{- end }}

            {{- if .Files.Glob "files/icinga2-report.conf" }}
            - name: icinga2-report-conf
              mountPath: /etc/icinga2-report/icinga2-report.conf
              subPath: icinga2-report.conf
            {{- end }}

            {{- if .Files.Glob "files/configuration/*.yml" }}
            - name: configuration
              mountPath: /etc/icinga2-report/configuration
            {{- end }}

            {{- if .Files.Glob "files/configuration/report_template/*" }}
            - name: report-template
              mountPath: /etc/icinga2-report/configuration/report_template
            {{- end }}

      volumes:
        {{- if .Values.datasources }}
        - name: datasources
          configMap:
            name: {{ include "common.names.fullname" . }}-datasources
        {{- end }}

        {{- if .Files.Glob "files/auth" }}
        - name: auth
          configMap:
            name: {{ include "common.names.fullname" . }}-auth
        {{- end }}

        {{- if .Files.Glob "files/icinga2-report.conf" }}
        - name: icinga2-report-conf
          configMap:
            name: {{ include "common.names.fullname" . }}-icinga2-report-conf
        {{- end }}

        {{- if .Files.Glob "files/configuration/*.yml" }}
        - name: configuration
          configMap:
            name: {{ include "common.names.fullname" . }}-configuration
        {{- end }}

        {{- if .Files.Glob "files/configuration/report_template/*" }}
        - name: report-template
          configMap:
            name: {{ include "common.names.fullname" . }}-report-template
        {{- end }}
