apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "common.names.fullname" . }}
type: Opaque
data:
  mtpPass: {{ ternary (randAlphaNum 10) .Values.mtpConfig.mtpPass (empty .Values.mtpConfig.mtpPass) | b64enc | quote  }}

