apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "common.names.fullname" . }}
type: Opaque
data:
  ui-password: {{ ternary (randAlphaNum 10) .Values.uiPassword (empty .Values.uiPassword) | b64enc | quote  }}

