apiVersion: v2
annotations:
  category: Preparation
name: preparation
description: SVTECH Preparation
engine: gotpl

dependencies:
  - name: common
    repository: file://../common
    tags:
      - bitnami-common
    version: 1.x.x

version: 1.0.0
appVersion: "v1.0.0"
