global:
  sharedVolume:
    enabled: false


commonAnnotations: {}

initRepo:
  image:
    repository: svtechnmaa/svtech_debuger
    tag: "latest"

    pullPolicy: IfNotPresent


  repoList: "moophat/SVTECH-Junos-Automation,moophat/SVTECH-Junos-Monitoring"
  # GH_TOKEN with Base64 encode
  GH_TOKEN: Z2hwX3pweThLUnZPZ0pXemtXNUdPUXIxSHFIN2JJTXIxMDNESkVhYQ==

nodeAffinityPreset:
  ## Node affinity type
  ## Allowed values: soft, hard
  type: ""
  ## Node label key to match
  ## E.g.
  ## key: "kubernetes.io/e2e-az-name"
  ##
  key: ""
  ## Node label values to match
  ## E.g.
  ## values:
  ##   - e2e-az1
  ##   - e2e-az2
  ##
  values: []


## Affinity for pod assignment
## Note: podAffinityPreset, podAntiAffinityPreset, and  nodeAffinityPreset will be ignored when it's set
##
affinity: {}
