FROM ubuntu:22.04

LABEL org.opencontainers.image.source=https://github.com/moophat/SVTECH_Projects_Container

RUN apt-get update && \
    apt-get -qq --no-install-recommends install -y net-tools iproute2 telnet openssh-server vim iputils-ping dnsutils curl wget tcpdump git apt-transport-https ca-certificates mysql-client && \
    update-ca-certificates && \
    apt-get clean all

RUN mkdir /var/run/sshd
RUN echo 'root:juniper@123' | chpasswd
RUN sed -i 's/#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
# RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
