{
 "title": "thruk",
 "tags": [ " embedded" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Device name",
    "query": "SHOW TAG VALUES from hostalive  WITH KEY = \"hostname\""
   },
   {
    "name": "address",
    "label": "IP address",
    "query": "SHOW TAG VALUES from hostalive  WITH KEY = \"address\" where device_type =~ /$device_type/  and hostname =~ /$hostname/ "
   },
   {
    "name": "service",
    "query": "SHOW TAG VALUES from ping4, snmp, \"check-snmp-with-oid-text-index\" WITH KEY = \"service\" where hostname =~ /^$hostname$/"
   },
   {
    "name": "interfaces",
    "query": "SHOW TAG VALUES from \"Interface-check-command\" WITH KEY = \"service\" where hostname =~ /^$hostname$/"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU LOAD - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "CPU Load RE0 (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.CPU.*/" },
      { "condition": "AND", "key": "service_type", "operator": "=", "value": "CPU" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^CPU.*.RE0.*/" }
     ],
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "alias": "CPU Load RE1 (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.CPU.*/" },
      { "condition": "AND", "key": "service_type", "operator": "=", "value": "CPU" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^CPU.*.RE1.*/" }
     ],
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "MEMORY - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Memory RE0 Usage (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.Memory.*/" },
      { "condition": "AND", "key": "service_type", "operator": "=", "value": "MEMORY" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MEM_RE0" }
     ],
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "alias": "Memory RE1 Usage (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.Memory.*/" },
      { "condition": "AND", "key": "service_type", "operator": "=", "value": "MEMORY" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MEM_RE1" }
     ],
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "TEMPERATURE - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Temperature (C)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.Temperature.*/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "Temp_Chassis" }
     ],
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "alias": "Temperature RE0 (C)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.Temperature.*/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "TEMP_RE0" }
     ],
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "alias": "Temperature RE1 (C)",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^Juniper.*.Temperature.*/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "TEMP_RE1" }
     ],
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "$service - $hostname",
   "type": "graph",
   "description": "Separate dashboard for Delay and Jitter only (pktLoss use a different dashboard due to different unit)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "$service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "check-snmp-with-oid-text-index",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "service_type", "operator": "=", "value": "KPI" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "Delay" }
     ]
    },
    {
     "alias": "$service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "check-snmp-with-oid-text-index",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "service_type", "operator": "=", "value": "KPI" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "Jitter" }
     ]
    }
   ]
  },
  {
   "title": "$service - $hostname",
   "type": "graph",
   "description": "Separate dashboard for displaying pktLoss in Thruk only (Delay and Jitter use a different dashboard due to different unit)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "check-snmp-with-oid-text-index",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "service_type", "operator": "=", "value": "KPI" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "pktLoss" }
     ]
    }
   ]
  },
  {
   "title": "Ping4 - $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "rta",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ping4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "rta" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "ping4" }
     ]
    },
    {
     "alias": "pl",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ping4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "pl" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "ping4" }
     ]
    }
   ]
  },
  {
   "title": "BW - $hostname - $interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$hostname-Max-Inbit-$interfaces",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "query": "SELECT max(\"value\") FROM \"Interface-check-command\" WHERE (\"service\" =~ /^$interfaces$/ AND \"metric\" = 'in_bits' AND \"hostname\" =~ /^$hostname$/ AND \"service\" !~ '/.*.ae.*./') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$interfaces$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "in_bits" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "$hostname-Max-Outbit-$interfaces",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Interface-check-command",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$interfaces$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "out_bits" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "$hostname - $service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$hostname-$service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT max(\"value\") FROM \"Interface-check-command\" WHERE (\"service\" =~ /^$interfaces$/ AND \"metric\" = 'in_bits' AND \"hostname\" =~ /^$hostname$/ AND \"service\" !~ '/.*.ae.*./') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "$hostname - $service - (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$hostname-$service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT max(\"value\") FROM \"Interface-check-command\" WHERE (\"service\" =~ /^$interfaces$/ AND \"metric\" = 'in_bits' AND \"hostname\" =~ /^$hostname$/ AND \"service\" !~ '/.*.ae.*./') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}