# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: rundeck-var-hostpath
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# allowVolumeExpansion: true

---
{{- $basePath := .Values.global.basePath }}
{{- $namespace := .Release.Namespace }}

{{- range .Values.global.sharedPersistenceVolume }}
{{- if eq .storageClass "rundeck-var-hostpath" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ $namespace }}-rundeck-var-pv"
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ $namespace }}-rundeck-var-hostpath
  capacity:
    # storage: 10Gi 
    storage: {{ .storageSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    # path: /opt/shared/rundeck_var
    path: {{ $basePath }}/{{ $namespace }}/rundeck_var
{{- end }}

{{- end  }}
